### ISSUE TITLE
[Bug] Only store apps are visible in the apps section

### ISSUE THREAD

**Issue by rp1231** [michalleptuch/ink-workspace#12] opened 2022-04-28 23:28 UTC
Currently only store apps are visible in the apps section.
It would be nice to have the win32 apps in the list as well.
If not permanently, an option in the settings to show the win32 apps would be nice.

**Comment by michalleptuch** [comment] 2022-04-29 11:41
Hi, it's not a bug. Classic apps will be available in the future.
Currently, you can use this button to add classic app manually:

![image](https://user-images.githubusercontent.com/43097852/165937704-22ee6cf3-4226-429d-9b40-ebfbf924f701.png)

**Comment by michalleptuch** [comment] 2023-02-25 16:41
It will be included in Ink Workspace 2.0.

**Closed by michalleptuch** 2023-02-25 16:41 UTC
